#!/bin/bash
#set -x

# Export a couple of variables to make udev happy.
export XAUTHORITY=/home/user/.Xauthority
export DISPLAY=:0.0

# First let us guess to see if remote display is connected and VGA
RDISPLAY=`xrandr -q | grep " connected" | awk '{if ($1 ~ /VGA/) print $1}'`

# Test to see if our first guess was correct for RDISPLAY and if not try again
if [ -z "$RDISPLAY" ]; then
	# if nothing found for VGA1 try HDMI1
	RDISPLAY=`xrandr -q | grep " connected" | awk '{if ($1 ~ /HDMI/) print $1}'`
fi

# Now let us try to guess to see what the local display is connected to and first guess LVDS
LDISPLAY=`xrandr -q | grep " connected" | awk '{if ($1 ~ /LVDS/) print $1}'`

# Test to see if our first guess was correct and if not try again
if [ -z "$LDISPLAY" ]; then
	# if nothing found then next guess for eDP1
	LDISPLAY=`xrandr -q | grep " connected" | awk '{if ($1 ~ /eDP/) print $1}'`
fi

# Now if we have both a remote and local display configured lets try to configure them.
if [ -n "$RDISPLAY" ] && [ -n "$LDISPLAY" ]; then
	echo "Attempt turning on second display."
	xrandr --output $RDISPLAY --auto --right-of $LDISPLAY
else
	echo "** Failed to detect both local and remote displays. **"
fi
exit 0;
